<a href="https://colab.research.google.com/github/hrbolek/learning/blob/master/operanalyst/teorieher.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Teorie her (Game Theory)

Další online zdroje můžete nalézt [zde](http://euler.fd.cvut.cz/predmety/teorie_her/) či v angličtině [zde](http://euler.fd.cvut.cz/predmety/game_theory/).

## Rozdělení

Podle ceny
- hry s nulovým součtem
- hry s nenulovým součtem

Podle vzahu hráčů
- hry antagonistické
- hry kooperativní
- hry proti přírodě

Podle počtu strategií
- konečné hry
- nekonečné hry

## Maticové hry

Hra "Kámen-nůžky-papír"

3 strategie obou hráčů 
- kámen
- nůžky
- papír

Výsledek hry
- kámen vs. kámen = 0
- kámen vs. nůžky = 1
- kámen vs. papír = -1
- nůžky vs. kámen = -1
- nůžky vs. nůžky = 0
- nůžky vs. papír = 1
- papír vs. kámen = 1
- papír vs. nůžky = -1
- papír vs. papír = 0

Vyjádřeno v matici výher (odtud maticová hra)

$$H=\begin{pmatrix}
0 & 1 & -1 \\
-1 & 0 & 1 \\
1 & -1 & 0 
\end{pmatrix}$$

Strategie hráče A je představena řádky
$$h_1=\begin{pmatrix}
0 & 1 & -1
\end{pmatrix}$$

$$h_2=\begin{pmatrix}
-1 & 0 & 1
\end{pmatrix}$$

$$h_3=\begin{pmatrix}
1 & -1 & 0
\end{pmatrix}$$

Strategie hráče B je představena sloupci

$$g_1=\begin{pmatrix}
0 \\
-1 \\
1
\end{pmatrix}$$

$$g_2=\begin{pmatrix}
1 \\
0 \\
-1 
\end{pmatrix}$$

$$g_3=\begin{pmatrix}
-1 \\
1 \\
0
\end{pmatrix}$$

matice výher pro hráče B je zápornou transponovanou maticí matice výher pro hráče A

$$G=-H^T=\begin{pmatrix}
0 & 1 & -1 \\
-1 & 0 & 1 \\
1 & -1 & 0 
\end{pmatrix}$$

Všimněte si, že $H=G$.

Jestliže hráč A volí strategii $i$ a hráč B volí strategii $j$, potom výhra hráče A je dána prvkem $h_{ij}$ a výhra hráče B je dána prvkem $g_{ij}$. Protože $g_{ij} +h_{ij}=0$, klasifikujeme tuto hru jako hru s nulovým součtem.



## Čisté strategie

$$A=\begin{pmatrix}
4 & 3 & 2 & 5 \\
-10 & 2 & 0 & -1 \\
7 & 5 & 2 & 3 \\
0 & 8  & -4 & -5
\end{pmatrix}$$
V jednotlivých řádcích hledáme maximum a z takto získaných maxim vybereme minimum.
$$\overline v =\min_i \max_j a_{ij}=2$$
V jednotlivých sloupcích hledáme minimum a z takto získaných minim vybereme maximum.
$$\underline v = \max_i \min_j a_{ij}=2$$
Protože
$$\underline v = \overline v$$
má hra sedlový bod, cena hry je 
$$v=\underline v = \overline v$$
a optimální strategie pro prvního hráče je strategie č. 1, alternativně č. 3 
$$\begin{pmatrix}
4 & 3 & 2 & 6
\end{pmatrix}$$
pro druhého hráče je optimální strategií strategie č. 3
$$\begin{pmatrix}
2 \\
0 \\
2 \\
-4
\end{pmatrix}$$

Existence sedlového bodu znamená, že změnou strategie si žádný z hráčů nepolepší.


$$A=\begin{pmatrix}
5 & 1 \\
3 & 4
\end{pmatrix}$$

$$\overline v=\min_i \max_j a_{ij}=4$$

$$\underline v = \max_i \min_j a_{ij}=3$$

Hra nemá sedlový bod a nemá řešení v čistých strategiích.

## Smíšené strategie

### Optimální řešení ve smíšených strategiích

Hráč A volí smíšenou strategii $s^A=(s_1^A, s_2^A, ..., s_n^A)$. Hráč B volí smíšenou strategii $s^B=(s_1^B, s_2^B, ..., s_n^B)$.


$$max\{v:A^Ts^A- \begin{pmatrix}v \\
v \\
\vdots \\
v
\end{pmatrix} \ge 0, \sum_{i=1}^ns_i^A=1,s^A \ge 0, v \in R\}$$

$$min\{w:As^B- \begin{pmatrix}w \\
w \\
\vdots \\
w
\end{pmatrix} \le 0, \sum_{i=1}^ns_i^B=1,s^B \ge 0, w \in R\}$$





### Příklad

Vyřešte hru kámen-nůžky-papír

$$H=\begin{pmatrix}
0 & 1 & -1 \\
-1 & 0 & 1 \\
1 & -1 & 0 
\end{pmatrix}$$

$$f(s^A)=v \to max$$

$$\begin{matrix}
 & -s_2^A & +s_3^A & -v & \ge & 0 \\
 s_1^A & & -s_3^A & -v & \ge & 0 \\
 -s_1^A & +s_2^A & & -v & \ge & 0 \\
 s_1^A & +s_2^A & +s_3^A & &=& 1
\end{matrix}
$$


$$g(s^B)=w \to min$$

$$\begin{matrix}
 & s_2^B & -s_3^B & -w & \le & 0 \\
 -s_1^B & & +s_3^B & -w & \le & 0 \\
 s_1^B & -s_2^B & & -w & \le & 0 \\
 s_1^B & +s_2^B & +s_3^B & &=& 1
\end{matrix}
$$


### Řešení s využitím Pythonu

Příklad byl už v zadání popsán jako úloha lineárního programování, proto úlohu budeme takto řešit.

Uživatelsky velmi přívětivou knihovnou je knihovna ```pulp```. Níže uvedený řádek provede její instalaci.

In [91]:
!pip install pulp

Dále je třeba knihovnu do programu naimportovat.

In [92]:
from pulp import *

Prvním krokem je definice problému. V tomto případě budeme hledat maximum.

In [93]:
probA = LpProblem("Game", LpMaximize)

Dále nadefinujeme proměnné problému. Tři proměnné představují hledanou smíšenou strategii, čtvrtá proměnná představuje cenu hry. U jednotlivých proměnných určujeme interval, který definuje přípustné řešení. Pro prvku vektoru smíšení strategie je to interval $\lt 0;1\gt$. Pro hodnotu hry to bude interval $<-1; 1>$, což vyplývá z matice hry.

In [94]:
sA1 = LpVariable("sA1", 0, 1)
sA2 = LpVariable("sA2", 0, 1)
sA3 = LpVariable("sA3", 0, 1)
v = LpVariable("v", -1, 1)

Nadefinujeme omezující podmínky. Zde vynikne uživatelská přívětivost knihovnu ```pulp``` nejvíce, neboť podmínky jsou zapisovány v intuitivním tvaru. 

In [95]:
probA += (-sA2+sA3-v >= 0)
probA += (sA1-sA3-v >= 0)
probA += (-sA1+sA2-v >= 0)
probA += (sA1+sA2+sA3 == 1)
probA += (v)

Následně spustíme řešení.

In [96]:
status = probA.solve()

A získáme hodnoty výpočtu.

In [97]:
print(f'sA1={value(sA1)}, sA2={value(sA2)}, sA3={value(sA3)}, v={value(v)}')
print(LpStatus[status])

sA1=0.33333333, sA2=0.33333333, sA3=0.33333333, v=0.0
Optimal


Vidíme, že hledanou smíšenou strategií je 

$$s^A=\left (\frac{1}{3}, \frac{1}{3}, \frac{1}{3} \right )$$

a že hodnota hry je

$$v=0$$

### Příklad II

Tento příklad je zamýšlen jako misto, kde v interaktivním módu tohoto textu můžete vyřešit jakoukoliv maticovou hru.

$$A=\begin{pmatrix}
4 & 3 & 2 & 5 \\
-10 & 2 & 0 & -1 \\
7 & 5 & 2 & 3 \\
0 & 8  & -4 & -5
\end{pmatrix}$$

In [98]:
from pulp import *
probA = LpProblem("Game", LpMaximize)
sA1 = LpVariable("sA1", 0, 1)
sA2 = LpVariable("sA2", 0, 1)
sA3 = LpVariable("sA3", 0, 1)
sA4 = LpVariable("sA4", 0, 1)
v = LpVariable("v", -10, 10)
probA += (4*sA1-10*sA2+7*sA3-v >= 0)
probA += (3*sA1+2*sA3+5*sA3+8*sA4-v >= 0)
probA += (2*sA1+0*sA2+2*sA3-4*sA4-v >= 0)
probA += (5*sA1-1*sA2+3*sA3-5*sA4-v >= 0)
probA += (sA1+sA2+sA3+sA4 == 1)
probA += (v)
status = probA.solve()

print(f'sA1={value(sA1)}, sA2={value(sA2)}, sA3={value(sA3)}, sA4={value(sA4)}, v={value(v)}')
print(LpStatus[status])

sA1=1.0, sA2=0.0, sA3=0.0, sA4=0.0, v=2.0
Optimal


## Hra plukovníka Blotta

Plukovník Blotto a jeho protivník chtějí zaujmout dvě pozice a za tím účelem mají možnost provést rozložení svých sil určitým způsobem.

Jedná se o "starou" hru. Její řešení v obecné podobě dlouho nebylo známo. V roce 2016 se podařilo vyřešit [článek](https://sciencemag.cz/problem-plukovnika-blotta-vyresen/).

Předpokládejme, že plukovník Blotto má 4 pluky a jeho protivník 3 pluky. Oba mohou své pluky rozdělit mezi dvě pozice, které chtějí zaujmout. Výplata (odměna, či výhra) je určena následujícím způsobem. Jestliže počet pluků $x$ plukovníka Blotta je na dané pozici větší než počet pluků protivníka $y$, pak výplata je $y+1$. Jestliže počet pluků $x$ plukovníka Blotta je na dané pozici menší než počet pluků protivníka $y$, pak výplata je $-x-1$. Celková výplata je dána součtem výplat pro jednotlivé pozice.

Plukovník Blotto má možnost rozmístit své pluky 5 způsoby, zatímco protivník 4 způsoby. Výplaty pro plukovníka Blotta lze uspořádat do matice (tabulky)

$$\begin{matrix}
      & (3,0) & (0,3) & (2,1) & (1,2) \\
(4,0) & 4     & 0     & 2     & 1 \\
(0,4) & 0     & 4     & 1     & 2 \\
(3,1) & 1     & -1    & 3     & 0 \\
(1,3) & -1    & 1     & 0     & 3 \\
(2,2) & -2    & -2    & 2     & 2 
\end{matrix}$$

Předpokládejte, že plukovník Blotto bude své strategie volit náhodně s pravděpodobnostmi $x^B=(x_1^B,x_2^B,x_3^B,x_4^B,x_5^B)$ a protivník bude volit své strategie také náhodně s pravděpodobnostmi $x^P=(x_1^P,x_2^P,x_3^P,x_4^P)$.

Najděte strategii $x^B$, která maximalizuje výplatu $v$.

Najděte strategii $x^P$, která minimalizuje výplatu $w$.

In [99]:
from pulp import *
probA = LpProblem("Game", LpMaximize)
sA1 = LpVariable("sA1", 0, 1000)
sA2 = LpVariable("sA2", 0, 1000)
sA3 = LpVariable("sA3", 0, 1000)
sA4 = LpVariable("sA4", 0, 1000)
sA5 = LpVariable("sA5", 0, 1000)
v = LpVariable("v", -10, 10)
probA += (4*sA1+0*sA2+1*sA3-1*sA4-2*sA5-v >= 0)
probA += (0*sA1+4*sA2-1*sA3+1*sA4-2*sA5-v >= 0)
probA += (2*sA1+1*sA2+3*sA3+0*sA4+2*sA5-v >= 0)
probA += (1*sA1+2*sA2+0*sA3+3*sA4+2*sA5-v >= 0)
probA += (sA1+sA2+sA3+sA4+sA5 == 1)
probA += (v)
status = probA.solve()

print(f'sA1={value(sA1)}, sA2={value(sA2)}, sA3={value(sA3)}, sA4={value(sA4)}, sA5={value(sA5)}, v={value(v)}')
print(LpStatus[status])

sA1=0.44444444, sA2=0.44444444, sA3=0.0, sA4=0.0, sA5=0.11111111, v=1.5555556
Optimal


## Algoritmus řešení hry s pomocí iterací

Přestože v dnešní době, kdy máme k dispozici nástroje, které trivializují řešení her metodami lineárního programování, jeví se, že ostatní metody nedávají příliš smysl. Metoda iterací ovšem demonstruje, jak jednokroková hra může být převedea na hru vícekrokovou a jak takové řešení lze využít i pro jednokrokovou variantu.

In [100]:
import numpy as np
from numpy import argmax, array

### Pomocné funkce na hledání min a max

Tato funkce ze seznamu hodnot najde maximum a současně s ním vrátí i polohu (index) tohoto maxima.

In [101]:
def finMax(data):
  index = argmax(data)
  return data[index], index

### Výpočet matice výher protihráče

Předpokládá se při řešení hry jsou známy jak matice cen pro hráče $A$ tak i pro hráče $B$ a to i přesto, že se může jednat o hru s nulovým součtem, kde platí již dříve zmíněné

$$G=-H^T$$

Právě tento vztah je využit pro následující funkci.

In [102]:
def deriveMatrix(H):
  result = H.T * (-1)
  return result

Ověření na matici hry Kámen, nůžky, papír je jednoduché.

In [103]:
H = array([[0, 1, -1], [-1, 0, 1], [1, -1, 0]])
G = array([[0, 1, -1], [-1, 0, 1], [1, -1, 0]])

G2 = deriveMatrix(H)
print(H)
print(G)
print('G2:', '-'*10)
print(G2)

[[ 0  1 -1]
 [-1  0  1]
 [ 1 -1  0]]
[[ 0  1 -1]
 [-1  0  1]
 [ 1 -1  0]]
G2: ----------
[[ 0  1 -1]
 [-1  0  1]
 [ 1 -1  0]]


### Normalizace strategie

Postup, při kterém z četností vypočítáme pravděpodobnosti. Při iterativní metodě jsou sumarizovány celkové výhry vyplývající ze zvolených strategií (sumarizace vektorů výher přislušných zvoleným strategiím) a také jsou udržovány četnosti volených strategií. Právě na základě četností je následně počítána smíšená strategie.

In [104]:
def normalizeStrategy(strategy):
  return strategy / sum(strategy) 

### Cena hry

Pokud známe smíšené strategie obou hráčů 

$$s^A=(s_1^A, s_2^A, ..., s_n^A)$$

$$s^B=(s_1^B, s_2^B, ..., s_n^B)$$

a známe matici hry

$$A$$

potom

$$v=s^{A} \cdot A \cdot s^{BT}$$

Tuto hodnotu počítá následující funkce z četností strategií volených v průběhu iterativního výpočtu.

In [105]:
def gameValue(strategies, gameMatrices):
  strategyA = normalizeStrategy(strategies[0])
  strategyB = normalizeStrategy(strategies[1])
  gameA = gameMatrices[0]
  gameB = gameMatrices[1]
  return (strategyA @ gameA @ strategyB.T, strategyB @ gameB @ strategyA.T)

In [106]:
strategyA = array([1/3, 1/3, 1/3])
strategyB = array([1/3, 1/3, 1/3])
gameValue((strategyA, strategyB), (H, G))

(0.0, 0.0)

### Výstup informace o hře, včetně smíšených strategií

In [107]:
def printGame(strategies, gameMatrices):
  strategyA = normalizeStrategy(strategies[0])
  strategyB = normalizeStrategy(strategies[1])
  gameA = gameMatrices[0]
  gameB = gameMatrices[1]

  print('\t', end='')
  for item in strategyB:
    print(f'{item:.2f}\t', end='')
  print()
  for index, value in enumerate(strategyA):
    print(f'{value:.2f}\t', end='')
    for mItem in gameA[index]:
      print(f'{mItem}\t', end='')
    print()

#### Příklad použití

In [108]:
printGame((strategyA, strategyB), (H, G))

	0.33	0.33	0.33	
0.33	0	1	-1	
0.33	-1	0	1	
0.33	1	-1	0	


### Krok hráče

Hráč na základě předchozích tahů protihráče volí čistou strategii, která mu maximalizuje zisk. Tedy hledá strategii, která by mu přinesla celkově největší zisk, kdyby ji volil jako odpověď na všechny zaznamenané tahy soupeře.

Celkové zisky jsou dány

$$ \vec v = s^A \cdot G$$

$$s_A$$

je četnost strategií hráče $A$

$$G$$

je matice výher hráče $B$

strategie maximalizující zisk pro hráče $B$ je potom 

$$i: v^* = \max_i v_i$$

In [109]:
def playerStep(mixedStrategy, gameMatrix):
  costs = mixedStrategy @ gameMatrix
  maxValue, maxIndex = findMax(costs)
  return maxIndex

In [110]:
strategyCount = array([1, 1, 1])
print(playerStep(strategyCount, H))

0


### Jeden krok v iteraci hry

Jeden krok se skládá z tahů obou hráčů.

In [111]:
def gameStep(strategies, gameMatrices):
  strategyA = strategies[0]
  strategyB = strategies[1]

  gameA = gameMatrices[0]
  gameB = gameMatrices[1]

  #najdi strategii
  pureStrategyA = playerStep(strategyB, gameB)
  #poznamenej ji jako pouzitou
  strategyA[pureStrategyA] += 1

  #najdi strategii
  pureStrategyB = playerStep(strategyB, gameB)
  #poznamenej ji jako pouzitou
  strategyB[pureStrategyB] += 1

  return strategyA, strategyB

### Řešení hry

Matice hry Kámen, nůžky, papír pro oba hráče je

$$H=G=\begin{pmatrix}
0 & 1 & -1 \\
-1 & 0 & 1 \\
1 & -1 & 0
\end{pmatrix}$$



In [112]:
H = array([[0, 1, -1], [-1, 0, 1], [1, -1, 0]])
G = array([[0, 1, -1], [-1, 0, 1], [1, -1, 0]])

strategyA = array([1, 1, 1])
strategyB = array([1, 1, 1])
for index in range(1000):
  strategyA, strategyB = gameStep((strategyA, strategyB), (H, G))
  if index % 100 == 0:
    printGame((strategyA, strategyB), (H, G))
    print('-'*30)

	0.50	0.25	0.25	
0.50	0	1	-1	
0.25	-1	0	1	
0.25	1	-1	0	
------------------------------
	0.39	0.28	0.33	
0.39	0	1	-1	
0.28	-1	0	1	
0.33	1	-1	0	
------------------------------
	0.32	0.37	0.30	
0.32	0	1	-1	
0.37	-1	0	1	
0.30	1	-1	0	
------------------------------
	0.32	0.36	0.32	
0.32	0	1	-1	
0.36	-1	0	1	
0.32	1	-1	0	
------------------------------
	0.33	0.37	0.30	
0.33	0	1	-1	
0.37	-1	0	1	
0.30	1	-1	0	
------------------------------
	0.35	0.33	0.32	
0.35	0	1	-1	
0.33	-1	0	1	
0.32	1	-1	0	
------------------------------
	0.33	0.32	0.35	
0.33	0	1	-1	
0.32	-1	0	1	
0.35	1	-1	0	
------------------------------
	0.32	0.35	0.33	
0.32	0	1	-1	
0.35	-1	0	1	
0.33	1	-1	0	
------------------------------
	0.35	0.32	0.33	
0.35	0	1	-1	
0.32	-1	0	1	
0.33	1	-1	0	
------------------------------
	0.31	0.33	0.36	
0.31	0	1	-1	
0.33	-1	0	1	
0.36	1	-1	0	
------------------------------


### Obecná funkce pro řešení hry

In [113]:
def solveMatrixGame(gameMatrices, iterations = 10000):
  gameA = gameMatrices[0]
  gameB = gameMatrices[1]  
  strategyA = array([1] * len(gameA))
  strategyB = array([1] * len(gameB))
  for index in range(iterations):
    strategyA, strategyB = gameStep((strategyA, strategyB), (gameA, gameB))
  return strategyA, strategyB

#### Příklad použití

In [116]:
H = array([[0, 1, -1], [-1, 0, 1], [1, -1, 0]])
G = deriveMatrix(H)

strategyA, strategyB = solveMatrixGame((H, G))
printGame((strategyA, strategyB), (H, G))
v = gameValue((strategyA, strategyB), (H, G))
print(v)

	0.34	0.33	0.33	
0.34	0	1	-1	
0.33	-1	0	1	
0.33	1	-1	0	
(-8.673617379884035e-19, -8.673617379884035e-19)


## Řešení maticové hry se sedlovým bodem

$$A=\begin{pmatrix}
4 & 3 & 2 & 5 \\
-10 & 2 & 0 & -1 \\
7 & 5 & 2 & 3 \\
0 & 8  & -4 & -5
\end{pmatrix}$$

In [115]:
H = array([[4, 3, 2, 5], [-10, 2, 0, -1], [7, 5, 2, 3], [0, 8, -4, -5]])
G = deriveMatrix(H)

strategyA, strategyB = solveMatrixGame((H, G))
printGame((strategyA, strategyB), (H, G))
v = gameValue((strategyA, strategyB), (H, G))
print(v)

	0.00	1.00	0.00	0.00	
0.00	4	3	2	5	
1.00	-10	2	0	-1	
0.00	7	5	2	3	
0.00	0	8	-4	-5	
(1.9993004497521267, -1.9993004497521263)
